name: CI

on:
  pull_request:

jobs:
  java-gradle:
    name: Java-Gradle CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Build
        run: gradle build --no-daemon

  ts-npm:
    name: TypeScript-NPM CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Download dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
